require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 6.0
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false
